apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki-config.yaml: |
    server:
      http_listen_port: 3100
    auth_enabled: false
    common:
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
    schema_config:
      configs:
        - from: 2020-10-24
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    ruler:
      alertmanager_url: http://localhost:9093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels: { app: loki }
  template:
    metadata:
      labels: { app: loki }
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.9.8
        args: ['-config.file=/etc/loki/loki-config.yaml']
        ports:
        - containerPort: 3100
          name: http
        volumeMounts:
        - name: cfg
          mountPath: /etc/loki
        - name: data
          mountPath: /loki
      volumes:
      - name: cfg
        configMap:
          name: loki-config
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  selector: { app: loki }
  ports:
  - name: http
    port: 3100
    targetPort: http
