apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /run/promtail/positions.yaml
    clients:
      - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
    scrape_configs:
      - job_name: kubernetes-pods
        pipeline_stages:
          - cri: {}
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target: namespace
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target: pod
          - action: replace
            source_labels: [__meta_kubernetes_pod_container_name]
            target: container
          - action: replace
            replacement: "/var/log/containers/*$1*.log"
            separator: /
            source_labels: [__meta_kubernetes_pod_uid]
            target: __path__
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: monitoring
spec:
  selector:
    matchLabels: { app: promtail }
  template:
    metadata:
      labels: { app: promtail }
    spec:
      serviceAccountName: default
      containers:
      - name: promtail
        image: grafana/promtail:2.9.8
        args: ['-config.file=/etc/promtail/promtail.yaml']
        volumeMounts:
        - name: cfg
          mountPath: /etc/promtail
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: cfg
        configMap:
          name: promtail-config
      - name: varlog
        hostPath: { path: /var/log }
      - name: varlibdockercontainers
        hostPath: { path: /var/lib/docker/containers }
